packages:
  - packages/*
  - playground

catalog:
  '@ant-design/colors': 7.2.1
  '@ant-design/fast-color': ^3.0.0
  '@ant-design/icons-svg': ^4.4.2
  '@antfu/eslint-config': ^5.4.1
  '@emotion/hash': ^0.8.0
  '@emotion/unitless': ^0.7.5
  '@testing-library/jest-dom': ^5.17.0
  '@types/jsdom': ^27.0.0
  '@types/node': ^24.10.3
  '@types/stylis': ^4.2.7
  '@types/testing-library__jest-dom': ^5.14.9
  '@v-c/collapse': ^0.0.5
  '@v-c/color-picker': ^1.0.3
  '@v-c/mutate-observer': ^0.0.2
  '@v-c/qrcode': ^0.0.5
  '@v-c/resize-observer': ^1.0.2
  '@v-c/util': ^1.0.3
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.9.0
  csstype: ^3.2.3
  defu: ^6.1.4
  es-toolkit: 1.43.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.1.0
  esno: ^4.8.0
  jiti: ^2.6.1
  jsdom: ^27.3.0
  pinia: ^3.0.4
  pkg-types: ^2.3.0
  scroll-into-view-if-needed: ^3.1.0
  stylis: ^4.3.6
  tsdown: ^0.15.12
  typescript: ~5.9.3
  unocss: ^66.5.10
  vite-plugin-inspect: ^11.3.3
  vitest: ^3.2.4
  vue: ^3.5.25
  vue-router: ^4.6.4
  vue-tsc: ^3.1.8
