/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AAffix: typeof import('antdv-next')['Affix'];
        AButton: typeof import('antdv-next')['Button'];
        AAlert: typeof import('antdv-next')['Alert'];
        AAnchor: typeof import('antdv-next')['Anchor'];
        ASpace: typeof import('antdv-next')['Space'];
        ADivider: typeof import('antdv-next')['Divider'];
        ASpaceCompact: typeof import('antdv-next')['SpaceCompact'];
        AFlex: typeof import('antdv-next')['Flex'];
        AConfigProvider: typeof import('antdv-next')['ConfigProvider'];
        ACol: typeof import('antdv-next')['Col'];
        ARow: typeof import('antdv-next')['Row'];
        ABadge: typeof import('antdv-next')['Badge'];
        ABadgeRibbon: typeof import('antdv-next')['Badge']['Ribbon'];
        ATag: typeof import('antdv-next')['Tag'];
        ACheckableTag: typeof import('antdv-next')['CheckableTag'];
        ALayout: typeof import('antdv-next')['Layout'];
        ALayoutHeader: typeof import('antdv-next')['LayoutHeader'];
        ALayoutFooter: typeof import('antdv-next')['LayoutFooter'];
        ALayoutContent: typeof import('antdv-next')['LayoutContent'];
        ALayoutSider: typeof import('antdv-next')['LayoutSider'];
    }
}
